# Generated by Django 4.2 on 2023-06-09 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('password1', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('birthdate', models.DateField()),
                ('phoneno', models.CharField(max_length=10)),
                ('address', models.TextField(max_length=255)),
                ('address1', models.TextField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zip', models.IntegerField(max_length=5)),
            ],
        ),
    ]
