# Generated by Django 4.2 on 2023-06-09 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_alter_user_zip'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='zip',
            new_name='zip_code',
        ),
    ]
