# Generated by Django 4.2 on 2023-06-09 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0003_rename_zip_user_zip_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='password1',
            new_name='password',
        ),
    ]
