# Generated by Django 4.2 on 2023-06-18 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0009_alter_userprofile_phoneno'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_image',
            field=models.ImageField(default='default_user_icon.jpg', upload_to='profile_images'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phoneno',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
