# Generated by Django 4.2 on 2023-06-20 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0010_userprofile_profile_image_alter_userprofile_phoneno'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shoefeatures',
            old_name='subcolor1',
            new_name='subcolor',
        ),
        migrations.RemoveField(
            model_name='shoefeatures',
            name='subcolor2',
        ),
    ]
