# Generated by Django 4.2 on 2023-07-04 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0010_userprofile_profile_image_alter_userprofile_phoneno'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoeFeatures',
            fields=[
                ('product_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='product_id')),
                ('type1', models.CharField(max_length=255)),
                ('type2', models.CharField(max_length=255)),
                ('maincolor', models.CharField(max_length=255)),
                ('subcolor', models.CharField(max_length=255)),
                ('subcolor2', models.CharField(max_length=255)),
                ('size', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('brand', models.CharField(max_length=255)),
                ('productImage', models.URLField()),
                ('description', models.CharField(max_length=255)),
                ('productName', models.CharField(max_length=255)),
            ],
        ),
    ]
