# Generated by Django 4.2 on 2023-07-04 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0011_shoefeatures'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoefeatures',
            name='product_id',
        ),
        migrations.AddField(
            model_name='shoefeatures',
            name='id',
            field=models.BigAutoField(auto_created=True, default=None, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
