# Generated by Django 4.2 on 2023-06-20 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0011_rename_subcolor1_shoefeatures_subcolor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoefeatures',
            name='subcolor2',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
