# Generated by Django 4.2 on 2023-07-04 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0012_remove_shoefeatures_product_id_shoefeatures_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoefeatures',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
