# Generated by Django 4.2 on 2023-06-27 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0012_shoefeatures_subcolor2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShoeFeatures',
        ),
    ]
