# Generated by Django 4.2 on 2023-07-04 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0013_alter_shoefeatures_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shoefeatures',
            old_name='id',
            new_name='product_id',
        ),
    ]
