# Generated by Django 4.2 on 2023-06-27 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0013_delete_shoefeatures'),
        ('hello', '0014_shoefeatures'),
    ]

    operations = [
    ]
