# Generated by Django 4.2 on 2023-07-04 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0014_rename_id_shoefeatures_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoefeatures',
            name='InStock',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
