# Generated by Django 4.2 on 2023-07-07 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0017_m_cart_shoefeatures_short_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='m_cart',
            name='username',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
