# Generated by Django 4.2 on 2023-07-08 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0018_m_cart_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='womenshoefeatures',
            name='short_description',
        ),
    ]
