# Generated by Django 4.2 on 2023-07-08 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0019_remove_womenshoefeatures_short_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='womenshoefeatures',
            name='short_description',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
