# Generated by Django 4.2 on 2023-07-08 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0020_womenshoefeatures_short_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='m_cart',
            name='product_image',
            field=models.URLField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
