# Generated by Django 4.2 on 2023-07-08 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0021_m_cart_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='m_cart',
            name='main_color',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='m_cart',
            name='product_size',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='m_cart',
            name='sub_color',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
