# Generated by Django 4.2 on 2023-07-08 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0022_m_cart_main_color_m_cart_product_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoefeatures',
            name='product_idName',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
