# Generated by Django 4.2 on 2023-07-12 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0023_shoefeatures_product_idname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='m_cart',
            name='id',
        ),
        migrations.AddField(
            model_name='m_cart',
            name='product_id',
            field=models.IntegerField(default=None, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
