# Generated by Django 4.2 on 2023-07-13 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0024_remove_m_cart_id_m_cart_product_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='W_Cart',
            fields=[
                ('product_id', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('productName', models.CharField(max_length=255)),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product_quantity', models.PositiveIntegerField(default=1)),
                ('product_image', models.URLField(max_length=255)),
                ('main_color', models.CharField(max_length=255)),
                ('sub_color', models.CharField(max_length=255)),
                ('product_size', models.IntegerField()),
            ],
        ),
    ]
