# Generated by Django 4.2 on 2023-07-14 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0025_w_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='womenshoefeatures',
            name='product_idName',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
