# Generated by Django 4.2 on 2023-07-15 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0026_womenshoefeatures_product_idname'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderTracker',
            fields=[
                ('product_id', models.IntegerField(primary_key=True, serialize=False)),
                ('product_idName', models.CharField(max_length=255)),
                ('productName', models.CharField(max_length=255)),
                ('productStatus', models.CharField(default='Paid', max_length=255)),
                ('delivery_status', models.CharField(default='Ongoing', max_length=255)),
            ],
        ),
    ]
