# Generated by Django 4.2 on 2023-07-17 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0028_transaction'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Transaction',
            new_name='OrderTransaction',
        ),
    ]
