# Generated by Django 4.2 on 2023-07-17 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0029_rename_transaction_ordertransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordertransaction',
            name='created_by',
            field=models.DateTimeField(default=None),
            preserve_default=False,
        ),
    ]
