# Generated by Django 4.2 on 2023-07-17 07:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0030_ordertransaction_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordertransaction',
            name='created_by',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
