# Generated by Django 4.2 on 2023-07-17 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0032_alter_shoefeatures_maincolor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordertransaction',
            name='status',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
