# Generated by Django 4.2 on 2023-07-17 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0034_alter_ordertransaction_main_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordertransaction',
            name='total_amount_vat',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10),
            preserve_default=False,
        ),
    ]
