# Generated by Django 4.2 on 2023-07-18 05:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0035_ordertransaction_total_amount_vat'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('product_id', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('productName', models.CharField(max_length=255)),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product_quantity', models.PositiveIntegerField(default=1)),
                ('product_image', models.URLField(max_length=255)),
                ('main_color', models.CharField(default='Black', max_length=255)),
                ('sub_color', models.CharField(default='Black', max_length=255)),
                ('product_size', models.IntegerField()),
                ('status', models.CharField(default='Paid', max_length=255)),
                ('created_by', models.DateTimeField(default=django.utils.timezone.now)),
                ('delivery_status', models.CharField(default='Delivered', max_length=255)),
                ('total_amount_vat', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
