# Generated by Django 4.2 on 2023-07-18 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0036_history'),
    ]

    operations = [
        migrations.DeleteModel(
            name='History',
        ),
        migrations.DeleteModel(
            name='OrderTracker',
        ),
        migrations.AlterField(
            model_name='ordertransaction',
            name='delivery_status',
            field=models.CharField(choices=[('Ongoing', 'Ongoing'), ('Delivered', 'Delivered')], default='Ongoing', max_length=255),
        ),
    ]
