# Generated by Django 4.2 on 2023-07-19 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0037_delete_history_delete_ordertracker_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoefeatures',
            name='product_id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
