# Generated by Django 4.2 on 2023-07-19 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0038_alter_shoefeatures_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoefeatures',
            name='InStock',
            field=models.CharField(max_length=255),
        ),
    ]
