# Generated by Django 4.2 on 2023-07-19 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0039_alter_shoefeatures_instock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoefeatures',
            name='InStock',
            field=models.IntegerField(),
        ),
    ]
