# Generated by Django 4.2 on 2023-07-23 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0040_alter_shoefeatures_instock'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoefeatures',
            name='material',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
