# Generated by Django 4.2 on 2023-07-31 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0042_womenshoefeatures_material'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordertransaction',
            name='delivery_status',
            field=models.CharField(choices=[('Ongoing', 'Ongoing'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], default='Ongoing', max_length=255),
        ),
    ]
