# Generated by Django 4.2 on 2023-07-31 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0043_alter_ordertransaction_delivery_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordertransaction',
            name='delivery_status',
            field=models.CharField(choices=[('Ongoing', 'Ongoing'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], max_length=255),
        ),
        migrations.AlterField(
            model_name='ordertransaction',
            name='status',
            field=models.CharField(max_length=255),
        ),
    ]
