# Generated by Django 4.2 on 2023-07-31 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0044_alter_ordertransaction_delivery_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordertransaction',
            old_name='status',
            new_name='payment_method',
        ),
        migrations.AddField(
            model_name='m_cart',
            name='payment_method',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='w_cart',
            name='payment_method',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
