# Generated by Django 4.2 on 2023-07-31 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0045_rename_status_ordertransaction_payment_method_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='m_cart',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='w_cart',
            name='payment_method',
        ),
        migrations.AlterField(
            model_name='ordertransaction',
            name='delivery_status',
            field=models.CharField(choices=[('Ongoing', 'Ongoing'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], default='Ongoing', max_length=255),
        ),
        migrations.AlterField(
            model_name='ordertransaction',
            name='payment_method',
            field=models.CharField(choices=[('CreditCard', 'CreditCard'), ('CashOnDelivery', 'CashOnDelivery'), ('Unpaid', 'Unpaid')], max_length=255),
        ),
    ]
