# Generated by Django 4.2 on 2023-08-20 09:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0046_remove_m_cart_payment_method_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('available_quantity', models.IntegerField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='ordertransaction',
            options={'verbose_name': 'Order', 'verbose_name_plural': 'Orders'},
        ),
        migrations.AlterModelOptions(
            name='shoefeatures',
            options={'verbose_name': 'Men product', 'verbose_name_plural': 'Men products'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'User account', 'verbose_name_plural': 'User account'},
        ),
        migrations.AlterModelOptions(
            name='womenshoefeatures',
            options={'verbose_name': 'Women product', 'verbose_name_plural': 'Women products'},
        ),
        migrations.AlterField(
            model_name='ordertransaction',
            name='created_by',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Order date'),
        ),
        migrations.AlterField(
            model_name='ordertransaction',
            name='total_amount_vat',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total amount'),
        ),
        migrations.AlterField(
            model_name='shoefeatures',
            name='InStock',
            field=models.IntegerField(verbose_name='In stock'),
        ),
        migrations.AlterField(
            model_name='shoefeatures',
            name='brand',
            field=models.CharField(max_length=255, verbose_name='Brand'),
        ),
        migrations.AlterField(
            model_name='shoefeatures',
            name='material',
            field=models.CharField(max_length=255, verbose_name='Material'),
        ),
        migrations.AlterField(
            model_name='shoefeatures',
            name='productName',
            field=models.CharField(max_length=255, unique=True, verbose_name='Model'),
        ),
        migrations.AlterField(
            model_name='shoefeatures',
            name='product_idName',
            field=models.CharField(max_length=255, verbose_name='Product ID'),
        ),
        migrations.AlterField(
            model_name='womenshoefeatures',
            name='InStock',
            field=models.IntegerField(verbose_name='In stock'),
        ),
        migrations.AlterField(
            model_name='womenshoefeatures',
            name='brand',
            field=models.CharField(max_length=255, verbose_name='Brand'),
        ),
        migrations.AlterField(
            model_name='womenshoefeatures',
            name='material',
            field=models.CharField(max_length=255, verbose_name='Material'),
        ),
        migrations.AlterField(
            model_name='womenshoefeatures',
            name='productName',
            field=models.CharField(max_length=255, unique=True, verbose_name='Model'),
        ),
        migrations.AlterField(
            model_name='womenshoefeatures',
            name='product_id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='womenshoefeatures',
            name='product_idName',
            field=models.CharField(max_length=255, verbose_name='Product ID'),
        ),
    ]
