# Generated by Django 4.2 on 2023-08-21 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0047_wishlist_alter_ordertransaction_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='productImage',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
