# Generated by Django 4.2 on 2023-08-21 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0050_alter_wishlist_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='brand',
            field=models.CharField(default=None, max_length=255, verbose_name='Brand'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wishlist',
            name='material',
            field=models.CharField(default=None, max_length=255, verbose_name='Material'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wishlist',
            name='type2',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
