# Generated by Django 4.2 on 2023-08-21 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0051_wishlist_brand_wishlist_material_wishlist_type2'),
    ]

    operations = [
        migrations.AddField(
            model_name='m_cart',
            name='InStock',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
