# Generated by Django 4.2 on 2023-08-21 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0053_wishlist_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='id',
        ),
        migrations.AddField(
            model_name='wishlist',
            name='product_id',
            field=models.BigIntegerField(default=None, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
