# Generated by Django 4.2 on 2023-08-21 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0054_remove_wishlist_id_wishlist_product_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='product_id',
        ),
        migrations.AddField(
            model_name='wishlist',
            name='id',
            field=models.BigAutoField(auto_created=True, default=None, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
