# Generated by Django 4.2 on 2023-08-27 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0055_remove_wishlist_product_id_wishlist_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordertransaction',
            options={'verbose_name': 'Sales Management', 'verbose_name_plural': 'Sales Management'},
        ),
        migrations.AlterModelOptions(
            name='shoefeatures',
            options={'verbose_name': 'Men product ', 'verbose_name_plural': 'Men products'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'Profile Management', 'verbose_name_plural': 'Profile Management'},
        ),
        migrations.AlterField(
            model_name='ordertransaction',
            name='payment_method',
            field=models.CharField(choices=[('CreditCard', 'CreditCard'), ('CashOnDelivery', 'CashOnDelivery'), ('Cancelled', 'Cancelled')], max_length=255),
        ),
    ]
