# Generated by Django 4.2 on 2023-08-27 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0056_alter_ordertransaction_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='username',
        ),
    ]
