# Generated by Django 4.2 on 2023-08-27 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0057_remove_wishlist_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='username',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
