# Generated by Django 4.2 on 2023-08-28 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0058_wishlist_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='product_id',
            field=models.BigIntegerField(default=None),
            preserve_default=False,
        ),
    ]
