# Generated by Django 4.2 on 2023-08-28 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0059_wishlist_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoefeatures',
            name='product_id',
            field=models.BigIntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
