# Generated by Django 4.2 on 2023-09-02 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0060_alter_shoefeatures_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoefeatures',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
    ]
