# Generated by Django 4.2 on 2023-09-14 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0061_shoefeatures_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='womenshoefeatures',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
    ]
