# Generated by Django 4.2 on 2023-09-26 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0063_ordertransaction_order_ratings'),
    ]

    operations = [
        migrations.AddField(
            model_name='m_cart',
            name='order_ratings',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10, verbose_name='Order Ratings'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='w_cart',
            name='order_ratings',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10, verbose_name='Order Ratings'),
            preserve_default=False,
        ),
    ]
