# Generated by Django 4.2 on 2023-09-26 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0064_m_cart_order_ratings_w_cart_order_ratings'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoefeatures',
            name='order_ratings',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10, verbose_name='Order Ratings'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='womenshoefeatures',
            name='order_ratings',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10, verbose_name='Order Ratings'),
            preserve_default=False,
        ),
    ]
