# Generated by Django 4.2 on 2023-10-22 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0065_shoefeatures_order_ratings_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoefeatures',
            name='sim_score',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10, verbose_name='Similarity Score'),
            preserve_default=False,
        ),
    ]
